### PR TITLE
Fix loading/storing ini file in a wrong directory

### PR DESCRIPTION
**Pull request by liuxd17thu**
When using shader toggler in some games with a launcher, the ini file goes into the directory of launcher, instead of the same directory as the addon itself.
I made a easy fix, generally the same way as what REST did.

### CODE REVIEW

**Comment by FransBouma** [comment]
Thanks for the fix! I inlined the variable usage which are used once in DllMain() pre-merge :)

**Comment by blackwind** [comment]
Note that crosire himself recommends using [get_reshade_base_path()](https://crosire.github.io/reshade-docs/namespacereshade.html#a3dce5382c15212557359af6388d2f4be) for this.

**Comment by blackwind** [comment]
Just found a real-world use case for `get_reshade_base_path()`: I tried centralizing my add-ons in one folder using the folder selector at the top of the add-ons tab so I don't have to go around and replace all copies of all add-ons for each game when a new version is released. In this configuration and with this PR, `ShaderToggler.ini` predictably ends up in the centralized add-ons folder, meaning you can't have separate profiles for each game. The correct logic would be to store `ShaderToggler.ini` next to `ReShade.ini` wherever that's located, which `get_reshade_base_path()` should accomplish.

**Comment by FransBouma** [comment]
I didn't realize there was a way to have all addons in a central place! that's great, because I have all my shaders in a central place but the addons are copied around to each game. 

Good point!

**Comment by FransBouma** [comment]
@blackwind See #18 
I can't use the api method as in DllMain the runtime object isn't available and the ini file has to be read at startup. However using the host exe's path works fine with a central location of the addons: the ini file is stored at the right location, where the dxgi file is located as well (or the exe file, in case of vulkan with centralized storage of the reshade dll)

**Comment by blackwind** [comment]
Note, though, that the [`RESHADE_BASE_PATH_OVERRIDE`](https://github.com/crosire/reshade/blob/5c8b8f0993a46fcd2f471181b002fb7f549c33c5/source/dll_main.cpp#L85C13-L85C13) environment variable exists. This is how Special K makes ReShade dump its files into Special K's per-game profile folder, and that's where I expect add-on data to be stored as well. If the API can't be used, perhaps the environment variable itself could be checked for an override instead?

**Comment by FransBouma** [comment]
How nice I get info fed one info bit at a time so I can fix a fix on a fix. :( 

Will think about it

(edit) The ini file for shadertoggler is stored in the exe's folder, where it normally would reside, using special K or not. So I think that's enough for now.

**Pull request merged**
